/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import system.Community;
import system.CommunityHistory;
import system.Doctor;
import system.Hospital;
import system.Patient;
import system.Person;
import system.doctorDirectory;
import system.hospitalDirectory;
import system.patientDirectory;
import system.personDirectory;

/**
 *
 * @author parth
 */
public class Admin_1 extends javax.swing.JPanel {

    Doctor doctor;
    Patient patient;
    Hospital hospital;
    Person person;
    Community community; 
    doctorDirectory docHistory;
    patientDirectory patientHistory;
    hospitalDirectory hospHistory;
    personDirectory personHistory;
    CommunityHistory CommunityDetails;
    
    public Admin_1(Doctor doctor, Patient patient, Hospital hospital, Person person, Community community, 
                    doctorDirectory docHistory, patientDirectory patientHistory, hospitalDirectory hospHistory, 
                    personDirectory personHistory, CommunityHistory CommunityDetails) {
        initComponents();
        this.doctor = doctor;
        this.patient = patient;
        this.hospital = hospital;
        this.person = person;
        this.docHistory = docHistory; 
        this.patientHistory = patientHistory;
        this.hospHistory = hospHistory;
        this.personHistory = personHistory;
        this.CommunityDetails = CommunityDetails;
        this.community = community;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        DoctorPanel = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel6 = new javax.swing.JPanel();
        btnAddDoc = new javax.swing.JButton();
        btnManageDoc = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        PatientPanel = new javax.swing.JPanel();
        jSplitPane3 = new javax.swing.JSplitPane();
        jPanel8 = new javax.swing.JPanel();
        btnAddPat = new javax.swing.JButton();
        btnManagePat = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        HospitalPanel = new javax.swing.JPanel();
        jSplitPane4 = new javax.swing.JSplitPane();
        jPanel10 = new javax.swing.JPanel();
        btnAddHosp = new javax.swing.JButton();
        btnManageHosp = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        PersonPanel = new javax.swing.JPanel();
        jSplitPane5 = new javax.swing.JSplitPane();
        jPanel13 = new javax.swing.JPanel();
        btnAddPerson = new javax.swing.JButton();
        btnManagePerson = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        CommunityPanel = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        btnAddCommunity = new javax.swing.JButton();
        btnManageCommunity = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        jPanel6.setBackground(new java.awt.Color(0, 204, 255));

        btnAddDoc.setBackground(new java.awt.Color(204, 204, 204));
        btnAddDoc.setText("Add");
        btnAddDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDocActionPerformed(evt);
            }
        });

        btnManageDoc.setBackground(new java.awt.Color(204, 204, 204));
        btnManageDoc.setText("Manage");
        btnManageDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageDocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddDoc)
                    .addComponent(btnManageDoc))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(btnAddDoc)
                .addGap(44, 44, 44)
                .addComponent(btnManageDoc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane2.setLeftComponent(jPanel6);

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel7.setPreferredSize(new java.awt.Dimension(858, 600));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 858, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        jSplitPane2.setRightComponent(jPanel7);

        javax.swing.GroupLayout DoctorPanelLayout = new javax.swing.GroupLayout(DoctorPanel);
        DoctorPanel.setLayout(DoctorPanelLayout);
        DoctorPanelLayout.setHorizontalGroup(
            DoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        DoctorPanelLayout.setVerticalGroup(
            DoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Doctor Admin", DoctorPanel);

        jPanel8.setBackground(new java.awt.Color(0, 204, 255));

        btnAddPat.setBackground(new java.awt.Color(204, 204, 204));
        btnAddPat.setText("Add");
        btnAddPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPatActionPerformed(evt);
            }
        });

        btnManagePat.setBackground(new java.awt.Color(204, 204, 204));
        btnManagePat.setText("Manage");
        btnManagePat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddPat)
                    .addComponent(btnManagePat))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(btnAddPat)
                .addGap(44, 44, 44)
                .addComponent(btnManagePat)
                .addContainerGap(411, Short.MAX_VALUE))
        );

        jSplitPane3.setLeftComponent(jPanel8);

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 862, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        jSplitPane3.setRightComponent(jPanel9);

        javax.swing.GroupLayout PatientPanelLayout = new javax.swing.GroupLayout(PatientPanel);
        PatientPanel.setLayout(PatientPanelLayout);
        PatientPanelLayout.setHorizontalGroup(
            PatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 868, Short.MAX_VALUE)
        );
        PatientPanelLayout.setVerticalGroup(
            PatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane3)
        );

        jTabbedPane1.addTab("Patient Admin", PatientPanel);

        jPanel10.setBackground(new java.awt.Color(0, 204, 255));

        btnAddHosp.setBackground(new java.awt.Color(204, 204, 204));
        btnAddHosp.setText("Add");
        btnAddHosp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddHospActionPerformed(evt);
            }
        });

        btnManageHosp.setBackground(new java.awt.Color(204, 204, 204));
        btnManageHosp.setText("Manage");
        btnManageHosp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageHospActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddHosp)
                    .addComponent(btnManageHosp))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(btnAddHosp)
                .addGap(44, 44, 44)
                .addComponent(btnManageHosp)
                .addContainerGap(405, Short.MAX_VALUE))
        );

        jSplitPane4.setLeftComponent(jPanel10);

        jPanel11.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 684, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 644, Short.MAX_VALUE)
        );

        jSplitPane4.setRightComponent(jPanel11);

        javax.swing.GroupLayout HospitalPanelLayout = new javax.swing.GroupLayout(HospitalPanel);
        HospitalPanel.setLayout(HospitalPanelLayout);
        HospitalPanelLayout.setHorizontalGroup(
            HospitalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane4)
        );
        HospitalPanelLayout.setVerticalGroup(
            HospitalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HospitalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane4))
        );

        jTabbedPane1.addTab("Hospital Admin", HospitalPanel);

        jPanel13.setBackground(new java.awt.Color(0, 204, 255));

        btnAddPerson.setBackground(new java.awt.Color(204, 204, 204));
        btnAddPerson.setText("Add");
        btnAddPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPersonActionPerformed(evt);
            }
        });

        btnManagePerson.setBackground(new java.awt.Color(204, 204, 204));
        btnManagePerson.setText("Manage");
        btnManagePerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePersonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddPerson)
                    .addComponent(btnManagePerson))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(btnAddPerson)
                .addGap(44, 44, 44)
                .addComponent(btnManagePerson)
                .addContainerGap(411, Short.MAX_VALUE))
        );

        jSplitPane5.setLeftComponent(jPanel13);

        jPanel14.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 678, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        jSplitPane5.setRightComponent(jPanel14);

        javax.swing.GroupLayout PersonPanelLayout = new javax.swing.GroupLayout(PersonPanel);
        PersonPanel.setLayout(PersonPanelLayout);
        PersonPanelLayout.setHorizontalGroup(
            PersonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PersonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane5))
        );
        PersonPanelLayout.setVerticalGroup(
            PersonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane5)
        );

        jTabbedPane1.addTab("Person Admin", PersonPanel);

        btnAddCommunity.setBackground(new java.awt.Color(204, 204, 204));
        btnAddCommunity.setText("Add");
        btnAddCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCommunityActionPerformed(evt);
            }
        });

        btnManageCommunity.setBackground(new java.awt.Color(204, 204, 204));
        btnManageCommunity.setText("Manage");
        btnManageCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCommunityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnManageCommunity)
                    .addComponent(btnAddCommunity))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(btnAddCommunity)
                .addGap(87, 87, 87)
                .addComponent(btnManageCommunity)
                .addContainerGap(407, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 843, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel3);

        javax.swing.GroupLayout CommunityPanelLayout = new javax.swing.GroupLayout(CommunityPanel);
        CommunityPanel.setLayout(CommunityPanelLayout);
        CommunityPanelLayout.setHorizontalGroup(
            CommunityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        CommunityPanelLayout.setVerticalGroup(
            CommunityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        jTabbedPane1.addTab("Community Admin", CommunityPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDocActionPerformed
        // TODO add your handling code here:
        CreateDoctorJPanel createDoctorJPanel = new CreateDoctorJPanel(docHistory);
        jSplitPane2.setRightComponent(createDoctorJPanel);
    }//GEN-LAST:event_btnAddDocActionPerformed

    private void btnManageDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageDocActionPerformed
        // TODO add your handling code here:
        ReadDoctorJPanel readDoctorJPanel = new ReadDoctorJPanel(docHistory, doctor);
        jSplitPane2.setRightComponent(readDoctorJPanel);
    }//GEN-LAST:event_btnManageDocActionPerformed

    private void btnAddPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPatActionPerformed
        // TODO add your handling code here:
        CreatePatientJPanel createPatientJPanel = new CreatePatientJPanel(patientHistory, CommunityDetails);
        jSplitPane3.setRightComponent(createPatientJPanel);
    }//GEN-LAST:event_btnAddPatActionPerformed

    private void btnManagePatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePatActionPerformed
        // TODO add your handling code here:
        ReadPatientJPanel readPatientJPanel = new ReadPatientJPanel(patientHistory, patient, CommunityDetails);
        jSplitPane3.setRightComponent(readPatientJPanel);
    }//GEN-LAST:event_btnManagePatActionPerformed

    private void btnAddHospActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddHospActionPerformed
        // TODO add your handling code here:
        CreateHospitalJPanel createHospitalJPanel = new CreateHospitalJPanel(hospHistory);
        jSplitPane4.setRightComponent(createHospitalJPanel);
    }//GEN-LAST:event_btnAddHospActionPerformed

    private void btnManageHospActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageHospActionPerformed
        // TODO add your handling code here:
        ReadHospitalJPanel readHospitalJPanel = new ReadHospitalJPanel(hospHistory);
        jSplitPane4.setRightComponent(readHospitalJPanel);
    }//GEN-LAST:event_btnManageHospActionPerformed

    private void btnAddPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPersonActionPerformed
        // TODO add your handling code here:
        CreatePersonJPanel createPersonJPanel = new CreatePersonJPanel(personHistory);
        jSplitPane5.setRightComponent(createPersonJPanel);
    }//GEN-LAST:event_btnAddPersonActionPerformed

    private void btnManagePersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePersonActionPerformed
        // TODO add your handling code here:
        ReadPersonJPanel readPersonJPanel = new ReadPersonJPanel(personHistory, person);
        jSplitPane5.setRightComponent(readPersonJPanel);
    }//GEN-LAST:event_btnManagePersonActionPerformed

    private void btnAddCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCommunityActionPerformed
        // TODO add your handling code here:
        CreateCommunityJPanel createCommunityJPanel = new CreateCommunityJPanel(CommunityDetails);
        jSplitPane1.setRightComponent(createCommunityJPanel);
    }//GEN-LAST:event_btnAddCommunityActionPerformed

    private void btnManageCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCommunityActionPerformed
        // TODO add your handling code here:
        ReadCommunityJPanel readCommunityJPanel = new ReadCommunityJPanel(CommunityDetails);
        jSplitPane1.setRightComponent(readCommunityJPanel);
    }//GEN-LAST:event_btnManageCommunityActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CommunityPanel;
    private javax.swing.JPanel DoctorPanel;
    private javax.swing.JPanel HospitalPanel;
    private javax.swing.JPanel PatientPanel;
    private javax.swing.JPanel PersonPanel;
    private javax.swing.JButton btnAddCommunity;
    private javax.swing.JButton btnAddDoc;
    private javax.swing.JButton btnAddHosp;
    private javax.swing.JButton btnAddPat;
    private javax.swing.JButton btnAddPerson;
    private javax.swing.JButton btnManageCommunity;
    private javax.swing.JButton btnManageDoc;
    private javax.swing.JButton btnManageHosp;
    private javax.swing.JButton btnManagePat;
    private javax.swing.JButton btnManagePerson;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JSplitPane jSplitPane4;
    private javax.swing.JSplitPane jSplitPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
