/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

/**
 *
 * @author parth
 */
public class ReadPersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReadPersonJPanel
     */
    public ReadPersonJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbPerTitle = new javax.swing.JLabel();
        lbPerComm = new javax.swing.JLabel();
        lbPerId = new javax.swing.JLabel();
        txtPerComm = new javax.swing.JTextField();
        txtPerId = new javax.swing.JTextField();
        lbPerName = new javax.swing.JLabel();
        txtPerName = new javax.swing.JTextField();
        lbPerAge = new javax.swing.JLabel();
        txtPerAge = new javax.swing.JTextField();
        lbPerGen = new javax.swing.JLabel();
        txtPerGen = new javax.swing.JTextField();
        lbPerHouse = new javax.swing.JLabel();
        txtPerHouse = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        lbPerTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbPerTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPerTitle.setText("Person");

        lbPerComm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPerComm.setText("Community");

        lbPerId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPerId.setText(" Id");

        txtPerComm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPerCommActionPerformed(evt);
            }
        });

        lbPerName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPerName.setText("Name");

        txtPerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPerNameActionPerformed(evt);
            }
        });

        lbPerAge.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPerAge.setText("Age");

        txtPerAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPerAgeActionPerformed(evt);
            }
        });

        lbPerGen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPerGen.setText("Gender");

        txtPerGen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPerGenActionPerformed(evt);
            }
        });

        lbPerHouse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPerHouse.setText("House");

        txtPerHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPerHouseActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbPerTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbPerComm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbPerId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbPerName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbPerAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbPerGen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbPerHouse, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPerId)
                            .addComponent(txtPerName)
                            .addComponent(txtPerAge)
                            .addComponent(txtPerGen)
                            .addComponent(txtPerHouse)
                            .addComponent(txtPerComm, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(85, 85, 85))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(251, 251, 251))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbPerTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPerId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPerId, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPerName, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPerAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPerAge, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPerGen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPerGen, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbPerHouse, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbPerComm, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtPerHouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPerComm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addComponent(jButton1)
                .addContainerGap(134, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPerCommActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPerCommActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPerCommActionPerformed

    private void txtPerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPerNameActionPerformed

    private void txtPerAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPerAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPerAgeActionPerformed

    private void txtPerGenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPerGenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPerGenActionPerformed

    private void txtPerHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPerHouseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPerHouseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lbPerAge;
    private javax.swing.JLabel lbPerComm;
    private javax.swing.JLabel lbPerGen;
    private javax.swing.JLabel lbPerHouse;
    private javax.swing.JLabel lbPerId;
    private javax.swing.JLabel lbPerName;
    private javax.swing.JLabel lbPerTitle;
    private javax.swing.JTextField txtPerAge;
    private javax.swing.JTextField txtPerComm;
    private javax.swing.JTextField txtPerGen;
    private javax.swing.JTextField txtPerHouse;
    private javax.swing.JTextField txtPerId;
    private javax.swing.JTextField txtPerName;
    // End of variables declaration//GEN-END:variables
}
